services:
  station-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      openchargemap.api.key: ${OPENCHARGEMAP_API_KEY}
    depends_on:
      station-db:
        condition: service_healthy
    networks:
      - sparkflow-network

  station-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - station-mysql-data:/var/lib/mysql
    networks:
      - sparkflow-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  sparkflow-network:
    name: sparkflow-network

volumes:
  station-mysql-data: 