services:
  station-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      OPENCHARGEMAP_API_KEY: ${OPENCHARGEMAP_API_KEY}
      OPENCHARGEMAP_API_URL: ${OPENCHARGEMAP_API_URL}
      SPRING_DATASOURCE_URL: jdbc:mysql://station-db:3306/${MYSQL_DATABASE}?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      station-db:
        condition: service_healthy
    networks:
      - sparkflow-network

  station-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - station-mysql-data:/var/lib/mysql
    networks:
      - sparkflow-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  station-mysql-data: 

networks:
  sparkflow-network:
    external: true 