services:
  station-app:
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://station-db:3306/sparkflow_station?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

  station-db:
    ports:
      - "${DB_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=sparkflow_station 