name: Enable Auto-Merge

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pull_number = context.payload.pull_request.number;
            const mutation = `
              mutation EnableAutoMerge($pullRequestId: ID!, $mergeMethod: PullRequestMergeMethod!) {
                enablePullRequestAutoMerge(input: {
                  pullRequestId: $pullRequestId,
                  mergeMethod: $mergeMethod
                }) {
                  pullRequest {
                    autoMergeRequest {
                      enabledAt
                    }
                  }
                }
              }
            `;
            
            const variables = {
              pullRequestId: context.payload.pull_request.node_id,
              mergeMethod: "MERGE"
            };
            
            await github.graphql(mutation, variables);