name: Security and Quality Scan

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: 'maven'
    
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build and Run Dependency Check
      run: |
        ./mvnw clean verify org.owasp:dependency-check-maven:check -Ddependency-check.failBuildOnCVSS=7 -Ddependency-check.nvd.apiKey=${{ secrets.NVD_API_KEY }}
      env:
        SPRING_PROFILES_ACTIVE: test
        
    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dependency-check-report
        path: target/dependency-check-report.html
        
    - name: Start Spring Boot Application
      run: |
        nohup ./mvnw spring-boot:run -Dspring-boot.run.profiles=test &
        sleep 30  # Wait for application to start
        
    - name: OWASP ZAP Scan
      uses: zaproxy/action-full-scan@v0.4.0
      with:
        target: 'http://localhost:8081'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'
        
    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: zap-report
        path: zap-report.html
        
    - name: Stop Spring Boot Application
      if: always()
      run: |
        pkill -f spring-boot 